#!/bin/bash

submodule_path="swift-project-starter-impl"

get_latest_tag() {
    latest_tag=$(gh api \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        /repos/swiftty/swift-project-starter-impl/releases/latest | jq -r '.tag_name')
    echo "$latest_tag"
}

check_version() {
    latest_tag=$(get_latest_tag)
    if [ -z "$latest_tag" ]; then
        echo "Failed to fetch latest tag. Exiting..."
        exit 1
    fi

    current_tag=$(cat version)
    if [ "$current_tag" = "$latest_tag" ]; then
        echo "No updates available."
    else
        echo "New version available: $latest_tag"

        echo "$latest_tag" > version

        git checkout -b "release/$latest_tag"
        git add -u

        # update plugin code
        cp -r $submodule_path/Plugins/* Plugins
        git add Plugins

        git commit -m "Update $submodule_path version to $latest_tag"
        git push origin HEAD
    fi
}

check_version
